# Generated by Django 5.2.17 on 2026-09-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=250)),
                ('short_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
